# Generated by Django 5.0.6 on 2024-06-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasker',
            fields=[
                ('tasker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('price_per_hour', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=500)),
                ('tasker', models.ForeignKey(db_column='tasker_id_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.tasker')),
            ],
            options={
                'unique_together': {('tasker', 'name')},
            },
        ),
    ]
