# Generated by Django 5.0.6 on 2024-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
