# Generated by Django 5.0.6 on 2024-06-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasker',
            name='address_state',
            field=models.CharField(default='test state', max_length=50),
            preserve_default=False,
        ),
    ]
