# Generated by Django 5.0.6 on 2024-06-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tasker_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasker',
            old_name='services',
            new_name='service',
        ),
    ]
