# Generated by Django 5.0.6 on 2024-06-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tasker_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasker',
            name='price',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
