# Generated by Django 5.0.6 on 2024-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tasker_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasker',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
