# Generated by Django 5.0.6 on 2024-06-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='type',
            new_name='work',
        ),
    ]
