# Generated by Django 5.0.6 on 2024-06-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tasker_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasker',
            name='phone_no',
            field=models.CharField(default='9090909090', max_length=10),
            preserve_default=False,
        ),
    ]
