# Generated by Django 5.0.6 on 2024-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_type_company_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work',
            field=models.CharField(max_length=100),
        ),
    ]
