# Generated by Django 5.0.6 on 2024-06-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tasker_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasker',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasker',
            name='last_name',
            field=models.CharField(default='doe', max_length=50),
            preserve_default=False,
        ),
    ]
