# Generated by Django 5.0.6 on 2024-06-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_company_state_alter_user_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='tasker',
        ),
    ]
