# Generated by Django 5.0.6 on 2024-06-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tasker_alter_user_tasker_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
