# Generated by Django 5.0.6 on 2024-06-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasker',
            name='price',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
