# Generated by Django 5.0.6 on 2024-06-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tasker_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasker',
            old_name='price',
            new_name='price_per_hour',
        ),
    ]
