# Generated by Django 5.0.6 on 2024-06-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_price_tasker_price_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasker',
        ),
        migrations.AddField(
            model_name='tasker',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasker',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
