# Generated by Django 5.0.6 on 2024-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_user_tasker_tasker_email_tasker_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasker',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='about',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='tasker_id',
        ),
        migrations.RemoveField(
            model_name='tasker',
            name='work',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work',
        ),
        migrations.AddField(
            model_name='tasker',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasker',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
