# Generated by Django 5.0.6 on 2024-06-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasker',
            name='active',
        ),
    ]
