# Generated by Django 5.0.6 on 2024-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_tasker_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasker',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tasker',
            name='work',
            field=models.CharField(choices=[('Packers and Movers', 'Packers and Movers'), ('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Cleaning Services', 'Cleaning Services'), ('Carpenters', 'Carpenters'), ('Pest Control', 'Pest Control'), ('Painters', 'Painters'), ('AC Services', 'AC Services'), ('Gardening', 'Gardening'), ('Home Security', 'Home Security'), ('Laundry', 'Laundry'), ('Moving Services', 'Moving Services'), ('Home Cleaning', 'Home Cleaning'), ('Furniture Assembly', 'Furniture Assembly'), ('Computer Repair', 'Computer Repair'), ('Interior Design', 'Interior Design')], max_length=100),
        ),
    ]
