# Generated by Django 5.0.6 on 2024-06-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_login_user_added_date_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
