# Generated by Django 5.0.6 on 2024-06-26 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_desc', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'Requested'), (2, 'Booked'), (3, 'Cancelled'), (4, 'Rejected')])),
                ('tasker', models.ForeignKey(db_column='tasker_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
