# Generated by Django 5.0.6 on 2024-07-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('full_address', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='request.request')),
            ],
        ),
    ]
