# Generated by Django 5.0.6 on 2024-07-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_booking_date_request_service_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='service_data',
            field=models.DateTimeField(),
        ),
    ]
