# Generated by Django 5.0.6 on 2024-07-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_service_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='service_data',
            new_name='service_date',
        ),
    ]
