# Generated by Django 5.0.6 on 2024-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_rename_service_data_request_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requested'), (2, 'Booked'), (3, 'Cancelled'), (4, 'Rejected'), (5, 'Completed')]),
        ),
    ]
