# Generated by Django 5.0.6 on 2024-07-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='task',
        ),
        migrations.AddField(
            model_name='address',
            name='request',
            field=models.OneToOneField(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='request.request'),
            preserve_default=False,
        ),
    ]
