# Generated by Django 5.0.6 on 2024-06-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
