# Generated by Django 5.0.6 on 2024-07-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_customuser_price_per_day_alter_customuser_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skill_proof_pdf',
        ),
    ]
