# Generated by Django 5.0.6 on 2024-06-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0004_remove_customuser_address_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='authe_addresses',
        ),
    ]
