# Generated by Django 5.0.6 on 2024-06-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_alter_address_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
    ]
