# Generated by Django 5.0.6 on 2024-06-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0006_alter_address_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='authe_addresses',
        ),
    ]
