# Generated by Django 5.0.6 on 2024-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0010_taskerskillproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, choices=[('Less than 1 year', 'Less than 1 year'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('More than 3 years', 'More than 3 years')], max_length=20, null=True),
        ),
    ]
