# Generated by Django 5.0.6 on 2024-06-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0012_customuser_about_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='about',
        ),
    ]
