# Generated by Django 5.0.6 on 2024-06-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0013_remove_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
