# Generated by Django 5.0.6 on 2024-06-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0014_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill_proof_pdf',
            field=models.FileField(default=1, upload_to='tasker_skill_proofs/'),
            preserve_default=False,
        ),
    ]
