# Generated by Django 5.0.6 on 2024-06-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0015_customuser_skill_proof_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill_proof_pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
