# Generated by Django 5.0.6 on 2024-06-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0018_alter_customuser_skill_proof_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
