# Generated by Django 5.0.6 on 2024-06-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0019_alter_customuser_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskerskillproof',
            name='pdf',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
