# Generated by Django 5.0.6 on 2024-06-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0020_alter_taskerskillproof_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskerSkillProof',
        ),
    ]
