# Generated by Django 5.0.6 on 2024-06-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0021_delete_taskerskillproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill_proof_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tasker_skill_proofs/'),
        ),
    ]
