# Generated by Django 5.0.6 on 2024-06-28 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0023_alter_customuser_skill_proof_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskerSkillProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.CharField(blank=True, max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
