# Generated by Django 5.0.6 on 2024-06-28 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0024_taskerskillproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill_proof_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tasker_skill_proofs/'),
        ),
        migrations.AlterField(
            model_name='taskerskillproof',
            name='pdf',
            field=models.FileField(upload_to='tasker_skill_proofs/'),
        ),
        migrations.AlterField(
            model_name='taskerskillproof',
            name='tasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proofs', to=settings.AUTH_USER_MODEL),
        ),
    ]
