# Generated by Django 5.0.6 on 2024-06-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0025_alter_customuser_skill_proof_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill_proof_pdf',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='taskerskillproof',
            name='pdf',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
