# Generated by Django 5.0.6 on 2024-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0028_customuser_price_per_day_alter_customuser_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='price_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
