# Generated by Django 5.0.6 on 2024-07-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0029_alter_customuser_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='price_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
