# Generated by Django 5.0.6 on 2024-07-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0030_customuser_price_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='price_per_day',
            new_name='price_perday',
        ),
    ]
