# Generated by Django 5.0.6 on 2024-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0032_rename_price_perday_customuser_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
