# Generated by Django 5.0.6 on 2024-07-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0033_alter_customuser_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skill_proof_pdf',
        ),
    ]
